# components/report_generator.py
import io
import re
from datetime import datetime

import numpy as np
import pandas as pd

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    BaseDocTemplate, Frame, HRFlowable, Image,
    PageBreak, PageTemplate, Paragraph, Spacer, Table, TableStyle,
)

# ── Colour palette mirrors the app's dark theme ──────────────────────────────
PURPLE    = colors.HexColor('#667eea')
PURPLE_LT = colors.HexColor('#a78bfa')
GREEN     = colors.HexColor('#48bb78')
ORANGE    = colors.HexColor('#ed8936')
BLUE      = colors.HexColor('#4facfe')
RED_CLR   = colors.HexColor('#fc8181')
BG_DARK   = colors.HexColor('#0d0d2b')
BG_CARD   = colors.HexColor('#1a1a3e')
BG_ROW    = colors.HexColor('#161630')
TEXT_WHT  = colors.HexColor('#f7fafc')
TEXT_MUT  = colors.HexColor('#a0aec0')
BORDER    = colors.HexColor('#2d3748')


def _grade_color(grade):
    return {'A': GREEN, 'B': BLUE, 'C': ORANGE, 'D': RED_CLR}.get(grade, PURPLE)


# ── Shared paragraph styles ───────────────────────────────────────────────────
def _styles():
    def s(name, **kw):
        return ParagraphStyle(name, **kw)

    return {
        'h1': s('h1', fontSize=26, textColor=TEXT_WHT, fontName='Helvetica-Bold',
                 spaceAfter=4),
        'h2': s('h2', fontSize=13, textColor=PURPLE_LT, fontName='Helvetica-Bold',
                 spaceBefore=14, spaceAfter=6),
        'sub': s('sub', fontSize=11, textColor=PURPLE_LT, fontName='Helvetica',
                  spaceAfter=3),
        'body': s('body', fontSize=9, textColor=TEXT_WHT, fontName='Helvetica',
                   spaceAfter=5, leading=15),
        'muted': s('muted', fontSize=8, textColor=TEXT_MUT, fontName='Helvetica',
                    spaceAfter=3),
        'cap': s('cap', fontSize=8, textColor=TEXT_MUT,
                  fontName='Helvetica-Oblique', alignment=TA_CENTER),
        'kv': s('kv', fontSize=20, textColor=PURPLE, fontName='Helvetica-Bold',
                 alignment=TA_CENTER, spaceAfter=1),
        'kl': s('kl', fontSize=7, textColor=TEXT_MUT, fontName='Helvetica',
                 alignment=TA_CENTER),
    }


# ── Custom doc template: dark background + header/footer on every page ────────
class _Doc(BaseDocTemplate):

    def __init__(self, buf, dataset_name, **kw):
        super().__init__(buf, **kw)
        self._dataset = dataset_name
        frame = Frame(self.leftMargin, self.bottomMargin,
                      self.width, self.height, id='main')
        self.addPageTemplates([
            PageTemplate(id='main', frames=[frame], onPage=self._decorate)
        ])

    def _decorate(self, canv, doc):
        canv.saveState()
        w, h = A4

        # Dark page background
        canv.setFillColor(BG_DARK)
        canv.rect(0, 0, w, h, fill=1, stroke=0)

        # Purple top bar
        canv.setFillColor(PURPLE)
        canv.rect(0, h - 2.5*cm*0.15, w, 2.5*cm*0.15, fill=1, stroke=0)

        # Header text
        canv.setFont('Helvetica', 7.5)
        canv.setFillColor(TEXT_MUT)
        canv.drawString(doc.leftMargin, h - 1*cm, 'QueryMind Analytics Report')
        canv.drawRightString(w - doc.rightMargin, h - 1*cm, self._dataset)

        # Header rule
        canv.setStrokeColor(BORDER)
        canv.setLineWidth(0.4)
        canv.line(doc.leftMargin, h - 1.15*cm, w - doc.rightMargin, h - 1.15*cm)

        # Footer rule + text
        canv.line(doc.leftMargin, 1.4*cm, w - doc.rightMargin, 1.4*cm)
        canv.setFont('Helvetica-Oblique', 7.5)
        ts = datetime.now().strftime('%B %d, %Y  %H:%M')
        canv.drawString(doc.leftMargin, 0.8*cm,
                        f'Generated by QueryMind  |  {ts}')
        canv.drawRightString(w - doc.rightMargin, 0.8*cm,
                             f'Page {doc.page}')
        canv.restoreState()


# ── Reusable table builders ───────────────────────────────────────────────────
def _kpi_row(pairs, styles, usable_w):
    """Row of KPI boxes: [(label, value), ...]"""
    n   = len(pairs)
    cw  = [usable_w / n] * n
    hdr = [Paragraph(lbl.upper(), styles['kl'])  for lbl, _   in pairs]
    val = [Paragraph(str(v),      styles['kv'])  for _,   v   in pairs]
    t   = Table([hdr, val], colWidths=cw)
    t.setStyle(TableStyle([
        ('BACKGROUND',    (0, 0), (-1, -1), BG_CARD),
        ('BOX',           (0, 0), (-1, -1), 0.4, BORDER),
        ('INNERGRID',     (0, 0), (-1, -1), 0.4, BORDER),
        ('TOPPADDING',    (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('VALIGN',        (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    return t


def _data_table(headers, rows, usable_w, col_widths=None):
    """Dark-themed data table matching the app's glass-table style."""
    if col_widths is None:
        col_widths = [usable_w / len(headers)] * len(headers)

    th_style = ParagraphStyle('th', fontSize=8, textColor=PURPLE_LT,
                               fontName='Helvetica-Bold')
    td_style = ParagraphStyle('td', fontSize=8, textColor=TEXT_WHT,
                               fontName='Helvetica', leading=12)

    data = [[Paragraph(str(h), th_style) for h in headers]]
    for row in rows:
        data.append([Paragraph(str(cell), td_style) for cell in row])

    row_bgs = [
        ('BACKGROUND', (0, i), (-1, i), BG_CARD if i % 2 == 0 else BG_ROW)
        for i in range(1, len(rows) + 1)
    ]

    t = Table(data, colWidths=col_widths, repeatRows=1)
    t.setStyle(TableStyle([
        ('BACKGROUND',    (0, 0), (-1, 0), colors.HexColor('#1e1e4a')),
        ('LINEBELOW',     (0, 0), (-1, 0), 0.5, PURPLE),
        ('BOX',           (0, 0), (-1, -1), 0.4, BORDER),
        ('INNERGRID',     (0, 0), (-1, -1), 0.3, BORDER),
        ('TOPPADDING',    (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('LEFTPADDING',   (0, 0), (-1, -1), 7),
        ('VALIGN',        (0, 0), (-1, -1), 'TOP'),
    ] + row_bgs))
    return t


def _plotly_image(fig, usable_w):
    """Convert a Plotly figure to a ReportLab Image. Returns None if kaleido missing."""
    try:
        import plotly.io as pio
        png = pio.to_image(fig, format='png', width=900, height=420, scale=2)
        img_h = usable_w * (420 / 900)
        return Image(io.BytesIO(png), width=usable_w, height=img_h)
    except Exception:
        return None


# ── Main entry point ─────────────────────────────────────────────────────────
def generate_pdf_report(df, fi, health, kpis, data_summary,
                         cleaning_report=None, figures=None,
                         file_name='dataset'):
    """
    Build the complete QueryMind PDF report and return raw bytes.

    Parameters
    ----------
    df              : pd.DataFrame  — current (possibly cleaned) dataframe
    fi              : dict          — file_info from session state
    health          : dict          — from get_data_health_score()
    kpis            : list          — from session state kpis
    data_summary    : str | None    — AI executive summary
    cleaning_report : dict | None   — from generate_cleaning_report()
    figures         : list | None   — Plotly Figure objects for chart pages
    file_name       : str           — original uploaded filename
    """
    buf      = io.BytesIO()
    st       = _styles()
    story    = []
    usable_w = A4[0] - 4*cm

    doc = _Doc(
        buf, dataset_name=file_name,
        pagesize=A4,
        leftMargin=2*cm, rightMargin=2*cm,
        topMargin=2.2*cm, bottomMargin=2*cm,
    )

    # ─────────────────────────────────────────
    # 1. COVER
    # ─────────────────────────────────────────
    story.append(Spacer(1, 1.2*cm))
    story.append(Paragraph('QueryMind', st['h1']))
    story.append(Paragraph('Data Analytics Report', st['sub']))
    story.append(HRFlowable(width=usable_w, thickness=0.5,
                             color=PURPLE, spaceAfter=10))
    story.append(Spacer(1, 0.3*cm))

    for label, value in [
        ('Dataset',   fi.get('file_name', file_name)),
        ('Rows',      f"{fi.get('num_rows', len(df)):,}"),
        ('Columns',   str(fi.get('num_cols', len(df.columns)))),
        ('Generated', datetime.now().strftime('%B %d, %Y  %H:%M')),
    ]:
        story.append(Paragraph(
            f'<font color="#a78bfa"><b>{label}:</b></font>  {value}',
            st['body']
        ))

    # ─────────────────────────────────────────
    # 2. DATA QUALITY
    # ─────────────────────────────────────────
    story.append(Spacer(1, 0.5*cm))
    story.append(Paragraph('Data Quality', st['h2']))

    grade     = health.get('grade', 'C')
    gc        = _grade_color(grade)
    grade_lbl = health.get('label', 'Fair')
    overall   = health.get('overall', 0)

    grade_card = Table([[
        Paragraph(grade, ParagraphStyle(
            'g', fontSize=48, textColor=gc,
            fontName='Helvetica-Bold', alignment=TA_CENTER)),
        Paragraph(
            f'<font size="14" color="{gc.hexval()}">'
            f'<b>{grade_lbl}</b></font><br/>'
            f'<font size="10" color="#a0aec0">{overall}/100</font>',
            ParagraphStyle('gl', fontSize=14, textColor=gc,
                            fontName='Helvetica-Bold', leading=20)),
    ]], colWidths=[3*cm, usable_w - 3*cm])
    grade_card.setStyle(TableStyle([
        ('BACKGROUND',    (0, 0), (-1, -1), BG_CARD),
        ('BOX',           (0, 0), (-1, -1), 0.4, BORDER),
        ('TOPPADDING',    (0, 0), (-1, -1), 12),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
        ('LEFTPADDING',   (0, 0), (-1, -1), 16),
        ('VALIGN',        (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    story.append(grade_card)
    story.append(Spacer(1, 0.3*cm))

    # Metric breakdown
    breakdown = health.get('breakdown', {})
    if breakdown:
        bd_rows = []
        for metric, score in breakdown.items():
            filled  = int(score / 5)
            bar     = ('*' * filled) + ('-' * (20 - filled))
            bd_rows.append([metric.title(), bar, f'{score}/100'])
        story.append(_data_table(
            ['Metric', 'Visual', 'Score'],
            bd_rows, usable_w,
            col_widths=[4*cm, 9*cm, 3*cm]
        ))

    # ─────────────────────────────────────────
    # 3. DATASET STATISTICS
    # ─────────────────────────────────────────
    story.append(Spacer(1, 0.4*cm))
    story.append(Paragraph('Dataset Statistics', st['h2']))

    null_c = int(df.isnull().sum().sum())
    num_c  = int(df.select_dtypes(include=[np.number]).shape[1])
    mem_mb = round(df.memory_usage(deep=True).sum() / 1024 / 1024, 2)

    story.append(_kpi_row([
        ('Total Rows',     f"{len(df):,}"),
        ('Total Columns',  len(df.columns)),
        ('Numeric Cols',   num_c),
        ('Missing Values', null_c),
        ('Memory',         f'{mem_mb} MB'),
    ], st, usable_w))

    # Numeric describe() table
    numeric_df = df.select_dtypes(include=[np.number])
    if not numeric_df.empty:
        story.append(Spacer(1, 0.4*cm))
        story.append(Paragraph('Numeric Summary', st['h2']))
        desc   = numeric_df.describe().round(2)
        hdr    = ['Stat'] + list(desc.columns)
        d_rows = [[str(idx)] + [str(v) for v in row]
                  for idx, row in desc.iterrows()]
        cw     = [2.5*cm] + [(usable_w - 2.5*cm) / len(desc.columns)] * len(desc.columns)
        story.append(_data_table(hdr, d_rows, usable_w, col_widths=cw))

    # ─────────────────────────────────────────
    # 4. KEY KPIs
    # ─────────────────────────────────────────
    if kpis:
        story.append(Spacer(1, 0.4*cm))
        story.append(Paragraph('Key Metrics', st['h2']))
        pairs = [(k['label'], k['formatted_value']) for k in kpis[:6]]
        for i in range(0, len(pairs), 3):
            story.append(_kpi_row(pairs[i:i+3], st, usable_w))
            story.append(Spacer(1, 0.15*cm))

    # ─────────────────────────────────────────
    # 5. AI EXECUTIVE SUMMARY
    # ─────────────────────────────────────────
    if data_summary:
        story.append(PageBreak())
        story.append(Paragraph('AI Executive Summary', st['h2']))
        # Strip markdown bold/headers before rendering in PDF
        clean = re.sub(r'\*\*(.+?)\*\*', r'\1', data_summary)
        clean = re.sub(r'#{1,6}\s*', '', clean)
        clean = re.sub(r'\n{3,}', '\n\n', clean).strip()
        for para in clean.split('\n\n'):
            if para.strip():
                story.append(Paragraph(para.strip(), st['body']))
                story.append(Spacer(1, 0.15*cm))

    # ─────────────────────────────────────────
    # 6. CHARTS
    # ─────────────────────────────────────────
    if figures:
        story.append(PageBreak())
        story.append(Paragraph('Visual Analytics', st['h2']))
        charts_added = 0
        for fig in figures[:4]:
            img = _plotly_image(fig, usable_w)
            if img:
                story.append(img)
                story.append(Spacer(1, 0.4*cm))
                charts_added += 1
        if charts_added == 0:
            story.append(Paragraph(
                'Charts could not be embedded. '
                'Run  pip install kaleido  and regenerate the report.',
                st['muted']
            ))

    # ─────────────────────────────────────────
    # 7. CLEANING REPORT
    # ─────────────────────────────────────────
    if cleaning_report:
        cr = cleaning_report
        story.append(PageBreak())
        story.append(Paragraph('Smart Cleaning Report', st['h2']))
        story.append(_kpi_row([
            ('Nulls Filled',       cr['total_nulls_filled']),
            ('Duplicates Removed', cr['duplicates_removed']),
            ('Columns Changed',    cr['columns_changed']),
            ('Rows After Clean',   f"{cr['rows_after']:,}"),
        ], st, usable_w))

        story.append(Spacer(1, 0.4*cm))
        story.append(Paragraph('Per-Column Changes', st['h2']))

        cr_hdr = ['Column', 'Type', 'Nulls', 'Unique', 'Actions', 'Changed']
        cr_rows = []
        for col in cr['columns']:
            ns = (f"{col['nulls_before']} -> {col['nulls_after']} (-{col['nulls_filled']})"
                  if col['nulls_filled'] > 0 else str(col['nulls_before']))
            ts = (f"{col['dtype_before']} -> {col['dtype_after']}"
                  if col['dtype_before'] != col['dtype_after'] else col['dtype_before'])
            us = (f"{col['unique_before']} -> {col['unique_after']}"
                  if col['unique_before'] != col['unique_after']
                  else str(col['unique_before']))
            ac = ' | '.join(col['actions']) if col['actions'] else 'No changes'
            cr_rows.append([col['name'], ts, ns, us, ac,
                            'Yes' if col['changed'] else '-'])
        story.append(_data_table(
            cr_hdr, cr_rows, usable_w,
            col_widths=[3*cm, 2.5*cm, 2.5*cm, 2*cm, 4.5*cm, 1.5*cm]
        ))

    # ─────────────────────────────────────────
    # 8. COLUMN SCHEMA
    # ─────────────────────────────────────────
    story.append(PageBreak())
    story.append(Paragraph('Column Schema', st['h2']))
    schema_rows = [
        [col,
         str(df[col].dtype),
         str(df[col].count()),
         str(int(df[col].isnull().sum())),
         str(df[col].nunique())]
        for col in df.columns
    ]
    story.append(_data_table(
        ['Column', 'Type', 'Non-Null', 'Nulls', 'Unique Values'],
        schema_rows, usable_w,
        col_widths=[4*cm, 3*cm, 3*cm, 2.5*cm, 3.5*cm]
    ))

    doc.build(story)
    buf.seek(0)
    return buf.read()