# components/report_generator.py
"""
QueryMind PDF Report Generator — CANVAS-FIRST APPROACH
Cover page drawn entirely via canvas callbacks - guaranteed no overlap.
"""

import io
import re
import traceback
from datetime import datetime

import numpy as np
import pandas as pd

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.platypus import (
    SimpleDocTemplate, PageBreak, Paragraph, Spacer,
    Table, TableStyle, HRFlowable, Image
)
from reportlab.graphics.shapes import Drawing, Rect, String, Line
from reportlab.graphics.charts.piecharts import Pie

# ── Optional deps ─────────────────────────────────────────────────────────────
_MPL_AVAILABLE = False
try:
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    _MPL_AVAILABLE = True
except ImportError:
    pass

_KALEIDO_AVAILABLE = False
try:
    import plotly.io as _pio
    _KALEIDO_AVAILABLE = True
except ImportError:
    pass

# ── Dimensions ────────────────────────────────────────────────────────────────
PW, PH = A4          # 595 x 842 pts
LM = RM = 2.0 * cm
TM = 2.5 * cm
BM = 2.0 * cm
UW = PW - LM - RM    # usable width ~453 pts

# ── Colours ───────────────────────────────────────────────────────────────────
C_PURPLE   = colors.HexColor('#667eea')
C_PURPLT   = colors.HexColor('#a78bfa')
C_GREEN    = colors.HexColor('#48bb78')
C_ORANGE   = colors.HexColor('#ed8936')
C_BLUE     = colors.HexColor('#4facfe')
C_RED      = colors.HexColor('#fc8181')
C_BG       = colors.HexColor('#0d0d2b')
C_CARD     = colors.HexColor('#1a1a3e')
C_ROW      = colors.HexColor('#161630')
C_BAR_BG   = colors.HexColor('#2d3748')
C_HEAD     = colors.HexColor('#1e1e4a')
C_WHITE    = colors.HexColor('#f7fafc')
C_MUTED    = colors.HexColor('#a0aec0')
C_BORDER   = colors.HexColor('#2d3748')

PALETTE = [
    colors.HexColor('#667eea'), colors.HexColor('#a78bfa'),
    colors.HexColor('#43e97b'), colors.HexColor('#4facfe'),
    colors.HexColor('#f093fb'), colors.HexColor('#ed8936'),
    colors.HexColor('#fc8181'), colors.HexColor('#48bb78'),
]


def _grade_color(g):
    return {
        'A': C_GREEN, 'B': C_BLUE,
        'C': C_ORANGE, 'D': C_RED
    }.get(str(g).upper(), C_PURPLE)


def _fmt_num(v):
    try:
        a = abs(float(v))
        if a >= 1e6: return f'{v/1e6:.1f}M'
        if a >= 1e3: return f'{v/1e3:.1f}K'
        return f'{float(v):.1f}'
    except Exception:
        return str(v)


# ─────────────────────────────────────────────────────────────────────────────
# CANVAS PAGE DECORATORS
# ─────────────────────────────────────────────────────────────────────────────

def _draw_header_footer(canv, doc, fi_name):
    """Shared header/footer drawn on every page."""
    canv.saveState()

    # Background
    canv.setFillColor(C_BG)
    canv.rect(0, 0, PW, PH, fill=1, stroke=0)

    # Top purple bar
    canv.setFillColor(C_PURPLE)
    canv.rect(0, PH - 3, PW, 3, fill=1, stroke=0)

    # Header text
    canv.setFont('Helvetica', 7.5)
    canv.setFillColor(C_MUTED)
    canv.drawString(LM, PH - 1.4*cm, 'QueryMind Analytics Report')
    canv.drawRightString(PW - RM, PH - 1.4*cm, fi_name)

    # Header rule
    canv.setStrokeColor(C_BORDER)
    canv.setLineWidth(0.4)
    canv.line(LM, PH - 1.55*cm, PW - RM, PH - 1.55*cm)

    # Footer rule
    canv.line(LM, 1.3*cm, PW - RM, 1.3*cm)
    canv.setFont('Helvetica-Oblique', 7.5)
    ts = datetime.now().strftime('%B %d, %Y  %H:%M')
    canv.drawString(LM, 0.7*cm, f'Generated by QueryMind  |  {ts}')
    canv.drawRightString(PW - RM, 0.7*cm, f'Page {doc.page}')

    canv.restoreState()


def _make_cover_drawer(fi, health):
    """
    Returns an onFirstPage callback that draws the ENTIRE page 1
    content on the canvas — title, tagline, metadata, quality section.
    No Platypus paragraphs involved → zero overlap possible.
    """
    def _draw_cover(canv, doc):
        _draw_header_footer(canv, doc, fi.get('file_name', ''))
        canv.saveState()

        # ── Starting Y: just below the header rule ────────────────────────────
        y = PH - TM - 0.2*cm   # ~790 pts from bottom

        # ══ BRAND NAME ════════════════════════════════════════════════════════
        canv.setFont('Helvetica-Bold', 38)
        canv.setFillColor(C_WHITE)
        canv.drawString(LM, y, 'QueryMind')
        y -= 0.45*cm

        # ── Accent rule ───────────────────────────────────────────────────────
        canv.setStrokeColor(C_PURPLE)
        canv.setLineWidth(1.5)
        canv.line(LM, y, PW - RM, y)
        y -= 0.5*cm

        # ══ TAGLINE ═══════════════════════════════════════════════════════════
        canv.setFont('Helvetica', 14)
        canv.setFillColor(C_PURPLT)
        canv.drawString(LM, y, 'Data Analytics Report')
        y -= 0.9*cm

        # ══ METADATA BLOCK ════════════════════════════════════════════════════
        now  = datetime.now().strftime('%B %d, %Y  %H:%M')
        meta = [
            ('Dataset',   fi.get('file_name', '—')),
            ('Rows',      f"{fi.get('num_rows', 0):,}"),
            ('Columns',   str(fi.get('num_cols', 0))),
            ('Generated', now),
        ]
        lx = LM
        vx = LM + 2.2*cm
        for label, val in meta:
            canv.setFont('Helvetica-Bold', 9.5)
            canv.setFillColor(C_PURPLT)
            canv.drawString(lx, y, f'{label}:')
            canv.setFont('Helvetica', 9.5)
            canv.setFillColor(C_WHITE)
            canv.drawString(vx, y, val)
            y -= 0.52*cm

        y -= 0.5*cm  # gap before quality section

        # ══ DATA QUALITY HEADING ══════════════════════════════════════════════
        canv.setFont('Helvetica-Bold', 14)
        canv.setFillColor(C_PURPLT)
        canv.drawString(LM, y, 'Data Quality')
        y -= 0.55*cm

        # ══ GRADE PILL ════════════════════════════════════════════════════════
        grade     = str(health.get('grade', 'C')).upper()
        gc        = _grade_color(grade)
        grade_lbl = health.get('label', 'Fair')
        overall   = health.get('overall', 0)

        pill_h  = 1.8*cm
        pill_y  = y - pill_h

        # Pill card background
        canv.setFillColor(C_CARD)
        canv.roundRect(LM, pill_y, UW, pill_h, 5, fill=1, stroke=0)

        # Pill border in grade colour
        canv.setStrokeColor(gc)
        canv.setLineWidth(1.0)
        canv.roundRect(LM, pill_y, UW, pill_h, 5, fill=0, stroke=1)

        # ── Grade letter: centred in left 2.8cm ──────────────────────────────
        letter_w  = 2.8*cm
        letter_cx = LM + letter_w / 2
        # Vertical centre of pill
        pill_mid  = pill_y + pill_h / 2
        # For Helvetica-Bold at 42pt: cap-height ≈ 30pt, so centre offset = 15pt
        canv.setFont('Helvetica-Bold', 42)
        canv.setFillColor(gc)
        canv.drawCentredString(letter_cx, pill_mid - 15, grade)

        # Vertical divider
        canv.setStrokeColor(C_BORDER)
        canv.setLineWidth(0.5)
        div_x = LM + letter_w
        canv.line(div_x, pill_y + 8, div_x, pill_y + pill_h - 8)

        # ── Grade label + score: right of divider ─────────────────────────────
        tx = LM + letter_w + 0.45*cm
        # Grade label — upper 60% of pill
        canv.setFont('Helvetica-Bold', 15)
        canv.setFillColor(gc)
        canv.drawString(tx, pill_mid + 2, grade_lbl)
        # Score — lower 40% of pill
        canv.setFont('Helvetica', 9)
        canv.setFillColor(C_MUTED)
        canv.drawString(tx, pill_mid - 14, f'Overall Score: {overall}/100')

        y = pill_y - 0.3*cm

        # ══ METRIC PROGRESS BARS ══════════════════════════════════════════════
        breakdown = health.get('breakdown', {})
        if breakdown:
            bar_label_w = 3.0*cm
            bar_score_w = 2.2*cm
            bar_w       = UW - bar_label_w - bar_score_w
            bar_x       = LM + bar_label_w
            score_x     = bar_x + bar_w + 0.15*cm
            row_h       = 0.75*cm
            n_rows      = len(breakdown)
            table_h     = n_rows * row_h

            # Table background
            canv.setFillColor(C_CARD)
            canv.rect(LM, y - table_h, UW, table_h, fill=1, stroke=0)
            canv.setStrokeColor(C_BORDER)
            canv.setLineWidth(0.4)
            canv.rect(LM, y - table_h, UW, table_h, fill=0, stroke=1)

            for i, (metric, score) in enumerate(breakdown.items()):
                row_y = y - (i + 1) * row_h
                mid_y = row_y + row_h / 2

                # Row separator
                if i > 0:
                    canv.setStrokeColor(C_BORDER)
                    canv.setLineWidth(0.25)
                    canv.line(LM + 4, row_y + row_h,
                              LM + UW - 4, row_y + row_h)

                # Metric label
                canv.setFont('Helvetica', 8.5)
                canv.setFillColor(C_MUTED)
                canv.drawString(LM + 0.3*cm, mid_y - 4, metric.title())

                # Bar track
                track_h = 9
                track_y = mid_y - track_h / 2
                canv.setFillColor(C_BAR_BG)
                canv.roundRect(bar_x, track_y, bar_w, track_h,
                               3, fill=1, stroke=0)

                # Bar fill
                fc = (C_GREEN if score >= 90 else
                      C_BLUE  if score >= 75 else
                      C_ORANGE if score >= 60 else C_RED)
                fw = max(0, score / 100 * bar_w)
                if fw > 0:
                    canv.setFillColor(fc)
                    canv.roundRect(bar_x, track_y, fw, track_h,
                                   3, fill=1, stroke=0)

                # Score label
                canv.setFont('Helvetica-Bold', 8.5)
                canv.setFillColor(C_WHITE)
                canv.drawString(score_x, mid_y - 4, f'{score}/100')

        canv.restoreState()

    return _draw_cover


def _make_page_drawer(fi_name):
    """Returns an onLaterPages callback (header/footer only)."""
    def _draw(canv, doc):
        _draw_header_footer(canv, doc, fi_name)
    return _draw


# ─────────────────────────────────────────────────────────────────────────────
# REUSABLE TABLE BUILDERS
# ─────────────────────────────────────────────────────────────────────────────

def _st():
    """Return style dict."""
    def s(n, **kw): return ParagraphStyle(n, **kw)
    return {
        'h2':   s('h2',   fontSize=13,  textColor=C_PURPLT,
                  fontName='Helvetica-Bold', spaceBefore=10, spaceAfter=6),
        'body': s('body', fontSize=9,   textColor=C_WHITE,
                  fontName='Helvetica', spaceAfter=5, leading=15),
        'muted':s('muted',fontSize=8,   textColor=C_MUTED,
                  fontName='Helvetica', spaceAfter=3),
        'cap':  s('cap',  fontSize=7,   textColor=C_MUTED,
                  fontName='Helvetica-Oblique',
                  alignment=TA_CENTER, spaceAfter=3),
        'kv':   s('kv',   fontSize=19,  textColor=C_PURPLE,
                  fontName='Helvetica-Bold',
                  alignment=TA_CENTER, spaceAfter=1),
        'kl':   s('kl',   fontSize=7,   textColor=C_MUTED,
                  fontName='Helvetica', alignment=TA_CENTER),
    }


def _kpi_table(pairs, styles, width):
    n  = len(pairs)
    cw = [width / n] * n
    t  = Table(
        [[Paragraph(l.upper(), styles['kl']) for l, _ in pairs],
         [Paragraph(str(v),    styles['kv']) for _, v in pairs]],
        colWidths=cw,
    )
    t.setStyle(TableStyle([
        ('BACKGROUND',    (0,0),(-1,-1), C_CARD),
        ('BOX',           (0,0),(-1,-1), 0.4, C_BORDER),
        ('INNERGRID',     (0,0),(-1,-1), 0.4, C_BORDER),
        ('TOPPADDING',    (0,0),(-1,-1), 8),
        ('BOTTOMPADDING', (0,0),(-1,-1), 8),
        ('VALIGN',        (0,0),(-1,-1), 'MIDDLE'),
    ]))
    return t


def _data_table(headers, rows, width, col_widths=None, fsz=8):
    if col_widths is None:
        col_widths = [width / len(headers)] * len(headers)
    TH = ParagraphStyle('TH', fontSize=fsz,   textColor=C_PURPLT,
                         fontName='Helvetica-Bold')
    TD = ParagraphStyle('TD', fontSize=fsz-1, textColor=C_WHITE,
                         fontName='Helvetica', leading=12)
    data = [[Paragraph(str(h), TH) for h in headers]]
    for r in rows:
        data.append([Paragraph(str(c), TD) for c in r])
    bgs = [('BACKGROUND', (0,i),(-1,i),
            C_CARD if i%2==0 else C_ROW)
           for i in range(1, len(rows)+1)]
    t = Table(data, colWidths=col_widths, repeatRows=1)
    t.setStyle(TableStyle([
        ('BACKGROUND',    (0,0),(-1,0), C_HEAD),
        ('LINEBELOW',     (0,0),(-1,0), 0.5, C_PURPLE),
        ('BOX',           (0,0),(-1,-1), 0.4, C_BORDER),
        ('INNERGRID',     (0,0),(-1,-1), 0.3, C_BORDER),
        ('TOPPADDING',    (0,0),(-1,-1), 5),
        ('BOTTOMPADDING', (0,0),(-1,-1), 5),
        ('LEFTPADDING',   (0,0),(-1,-1), 6),
        ('VALIGN',        (0,0),(-1,-1), 'TOP'),
    ] + bgs))
    return t


# ─────────────────────────────────────────────────────────────────────────────
# NATIVE CHARTS
# ─────────────────────────────────────────────────────────────────────────────

def _bar_drawing(df, title, w, col=None, group_col=None):
    try:
        nc = df.select_dtypes(include=[np.number]).columns.tolist()
        cc = df.select_dtypes(include=['object','category']).columns.tolist()
        if not nc: return None
        if not col or col not in df.columns: col = nc[0]
        if not group_col and cc: group_col = cc[0]

        if group_col and group_col in df.columns:
            g = df.groupby(group_col)[col].sum().nlargest(8)
            labels = [str(x)[:12] for x in g.index]
            vals   = [float(v) for v in g.values]
        else:
            cnt, edges = np.histogram(df[col].dropna(), bins=8)
            labels = [f'{e:.0f}' for e in edges[:-1]]
            vals   = [float(c) for c in cnt]

        if not vals or max(vals) == 0: return None

        cw_ = float(w); ch = 185
        pl = 55; pb = 32; pt = 26; pr = 6
        pw_ = cw_ - pl - pr; ph = ch - pb - pt

        d = Drawing(cw_, ch)
        d.add(Rect(0,0,cw_,ch, fillColor=C_CARD,
                   strokeColor=C_BORDER, strokeWidth=0.5))

        mx = max(vals); n = len(vals)
        sw_ = pw_/n; bw_ = sw_*0.65; gap = (sw_-bw_)/2

        for i in range(5):
            gy = pb + ph*i/4
            d.add(Line(pl,gy,cw_-pr,gy,
                       strokeColor=C_BORDER, strokeWidth=0.3))
            d.add(String(pl-3, gy-3, _fmt_num(mx*i/4),
                         fontSize=5.5, fillColor=C_MUTED,
                         textAnchor='end'))

        for i,(lbl,val) in enumerate(zip(labels,vals)):
            bx  = pl + i*sw_ + gap
            bh_ = max(2, val/mx*ph)
            clr = PALETTE[i % len(PALETTE)]
            d.add(Rect(bx,pb,bw_,bh_, fillColor=clr, strokeColor=None))
            d.add(String(bx+bw_/2, pb+bh_+2, _fmt_num(val),
                         fontSize=5, fillColor=C_WHITE, textAnchor='middle'))
            d.add(String(bx+bw_/2, pb-12, lbl[:10],
                         fontSize=5.5, fillColor=C_MUTED, textAnchor='middle'))

        d.add(String(cw_/2, ch-14, title, fontSize=8.5, fillColor=C_WHITE,
                     fontName='Helvetica-Bold', textAnchor='middle'))
        return d
    except Exception:
        print(f'[PDF] bar "{title}":\n{traceback.format_exc()}')
        return None


def _pie_drawing(df, title, w, col=None, group_col=None):
    try:
        nc = df.select_dtypes(include=[np.number]).columns.tolist()
        cc = df.select_dtypes(include=['object','category']).columns.tolist()
        if not nc or not cc: return None
        if not col or col not in df.columns: col = nc[0]
        if not group_col: group_col = cc[0]
        if group_col not in df.columns: return None

        g = df.groupby(group_col)[col].sum().nlargest(6)
        if g.empty: return None
        labels = [str(x)[:16] for x in g.index]
        vals   = [float(v) for v in g.values]
        total  = sum(vals)

        cw_ = float(w); ch = 185
        d = Drawing(cw_, ch)
        d.add(Rect(0,0,cw_,ch, fillColor=C_CARD,
                   strokeColor=C_BORDER, strokeWidth=0.5))
        d.add(String(cw_/2, ch-14, title, fontSize=8.5, fillColor=C_WHITE,
                     fontName='Helvetica-Bold', textAnchor='middle'))

        pie = Pie()
        pie.x=30; pie.y=22; pie.width=120; pie.height=120
        pie.data   = vals
        pie.labels = [f'{v/total*100:.1f}%' for v in vals]
        pie.sideLabels=True; pie.sideLabelsOffset=0.08
        pie.simpleLabels=False
        for i in range(len(vals)):
            pie.slices[i].fillColor   = PALETTE[i%len(PALETTE)]
            pie.slices[i].strokeColor = C_BG
            pie.slices[i].strokeWidth = 0.5
            pie.slices[i].fontSize    = 5.5
            pie.slices[i].fontColor   = C_WHITE
        d.add(pie)

        lx = 188
        for i,(lbl,val) in enumerate(zip(labels,vals)):
            ly = ch-36-i*20
            if ly < 12: break
            d.add(Rect(lx,ly,9,9,
                       fillColor=PALETTE[i%len(PALETTE)],
                       strokeColor=None))
            d.add(String(lx+13, ly+1, f'{lbl}: {_fmt_num(val)}',
                         fontSize=6.5, fillColor=C_WHITE, textAnchor='start'))
        return d
    except Exception:
        print(f'[PDF] pie "{title}":\n{traceback.format_exc()}')
        return None


def _mpl_img(df, title, w, ctype='bar', col=None, gc=None):
    if not _MPL_AVAILABLE: return None
    try:
        nc = df.select_dtypes(include=[np.number]).columns.tolist()
        if not nc: return None
        if not col or col not in df.columns: col = nc[0]
        cc = df.select_dtypes(include=['object','category']).columns.tolist()
        if not gc and cc: gc = cc[0]

        fig, ax = plt.subplots(figsize=(8, 3), facecolor='#0d0d2b')
        ax.set_facecolor('#1a1a3e')
        if ctype == 'bar' and gc and gc in df.columns:
            g = df.groupby(gc)[col].sum().nlargest(10)
            ax.bar(g.index.astype(str), g.values,
                   color='#667eea', edgecolor='#2d3748', lw=0.4)
        else:
            ax.hist(df[col].dropna(), bins=20,
                    color='#667eea', edgecolor='#2d3748', lw=0.4)
        ax.set_title(title, color='#f7fafc', fontsize=9, pad=5)
        ax.tick_params(colors='#a0aec0', labelsize=7)
        for sp in ax.spines.values(): sp.set_edgecolor('#2d3748')
        plt.xticks(rotation=25, ha='right')
        plt.tight_layout(pad=0.3)
        buf = io.BytesIO()
        fig.savefig(buf, format='png', dpi=130,
                    facecolor='#0d0d2b', bbox_inches='tight')
        plt.close(fig)
        buf.seek(0)
        return Image(buf, width=w, height=w*3/8)
    except Exception:
        print(f'[PDF] mpl "{title}":\n{traceback.format_exc()}')
        return None


# ─────────────────────────────────────────────────────────────────────────────
# CHART SECTION — single column, max 4 charts
# ─────────────────────────────────────────────────────────────────────────────

def _add_charts(story, df, styles, figures=None):
    nc = df.select_dtypes(include=[np.number]).columns.tolist()
    cc = df.select_dtypes(include=['object','category']).columns.tolist()

    items = []   # (flowable, caption)

    # 1. Plotly/kaleido
    if figures and _KALEIDO_AVAILABLE:
        for fig in figures[:4]:
            try:
                png = _pio.to_image(fig, format='png',
                                    width=860, height=380, scale=2)
                img = Image(io.BytesIO(png), width=UW, height=UW*380/860)
                items.append((img, ''))
            except Exception:
                pass

    # 2. matplotlib
    if len(items) < 4 and _MPL_AVAILABLE:
        specs = []
        if cc and nc:
            specs.append(('bar',  nc[0], cc[0], f'{nc[0]} by {cc[0]}'))
        if nc:
            specs.append(('hist', nc[0], None,  f'Distribution – {nc[0]}'))
        if len(nc) >= 2:
            specs.append(('hist', nc[1], None,  f'Distribution – {nc[1]}'))
        if len(cc) >= 2 and len(nc) >= 2:
            specs.append(('bar',  nc[1], cc[1], f'{nc[1]} by {cc[1]}'))
        for ct, c, g, ttl in specs[:4-len(items)]:
            img = _mpl_img(df, ttl, UW, ctype=ct, col=c, gc=g)
            if img: items.append((img, ttl))

    # 3. ReportLab native
    if len(items) < 4:
        specs = []
        if cc and nc:
            specs.append(('bar', nc[0], cc[0], f'{nc[0]} by {cc[0]}'))
        if cc and nc:
            specs.append(('pie', nc[0], cc[0], f'{cc[0]} – {nc[0]} share'))
        if len(nc) >= 2 and cc:
            specs.append(('bar', nc[1], cc[0], f'{nc[1]} by {cc[0]}'))
        if len(cc) >= 2 and len(nc) >= 2:
            specs.append(('pie', nc[1], cc[1], f'{cc[1]} – {nc[1]} share'))
        for ct, c, g, ttl in specs[:4-len(items)]:
            drw = (_bar_drawing(df, ttl, UW, col=c, group_col=g)
                   if ct == 'bar'
                   else _pie_drawing(df, ttl, UW, col=c, group_col=g))
            if drw is not None:
                items.append((drw, ttl))

    if not items:
        story.append(Paragraph(
            'No charts could be generated.', styles['muted']))
        return

    cap_s = ParagraphStyle('cap2', fontSize=7, textColor=C_MUTED,
                           fontName='Helvetica-Oblique',
                           alignment=TA_CENTER, spaceAfter=6)
    for fl, cap in items:
        story.append(fl)
        if cap:
            story.append(Paragraph(cap, cap_s))
        story.append(Spacer(1, 0.3*cm))


# ─────────────────────────────────────────────────────────────────────────────
# MAIN ENTRY POINT
# ─────────────────────────────────────────────────────────────────────────────

def generate_pdf_report(df, fi, health, kpis, data_summary,
                         cleaning_report=None, figures=None,
                         file_name='dataset'):
    """Build and return QueryMind PDF as raw bytes."""

    buf      = io.BytesIO()
    styles   = _st()
    fi_name  = fi.get('file_name', file_name)

    # ── Build page callback closures ──────────────────────────────────────────
    on_first = _make_cover_drawer(fi, health)
    on_later = _make_page_drawer(fi_name)

    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=LM, rightMargin=RM,
        topMargin=TM,  bottomMargin=BM,
        title='QueryMind Analytics Report',
        author='QueryMind',
    )

    story = []

    # ── PAGE 1: blank spacer (cover drawn by onFirstPage) ─────────────────────
    # We push a full-page spacer so Platypus emits page 1 and moves to page 2.
    # onFirstPage fires BEFORE Platypus draws anything, so the canvas is clear.
    story.append(Spacer(1, PH - TM - BM - 1))

    # ── PAGE 2: Statistics ────────────────────────────────────────────────────
    story.append(PageBreak())
    story.append(Paragraph('Dataset Statistics', styles['h2']))

    null_c = int(df.isnull().sum().sum())
    num_c  = int(df.select_dtypes(include=[np.number]).shape[1])
    mem_mb = round(df.memory_usage(deep=True).sum() / 1024**2, 2)

    story.append(_kpi_table([
        ('Total Rows',     f'{len(df):,}'),
        ('Total Columns',  len(df.columns)),
        ('Numeric Cols',   num_c),
        ('Missing Values', null_c),
        ('Memory',         f'{mem_mb} MB'),
    ], styles, UW))
    story.append(Spacer(1, 0.4*cm))

    ndf = df.select_dtypes(include=[np.number])
    if not ndf.empty:
        story.append(Paragraph('Numeric Summary', styles['h2']))
        desc = ndf.describe().round(2)
        abbr = {c: (c[:8]+'…' if len(c)>9 else c) for c in desc.columns}
        desc.columns = [abbr[c] for c in desc.columns]
        sw  = 2.2*cm
        cw_ = (UW - sw) / len(desc.columns)
        story.append(_data_table(
            ['Stat'] + list(desc.columns),
            [[str(i)] + [str(v) for v in r]
             for i, r in desc.iterrows()],
            UW, col_widths=[sw]+[cw_]*len(desc.columns), fsz=7,
        ))
        story.append(Spacer(1, 0.4*cm))

    if kpis:
        story.append(Paragraph('Key Metrics', styles['h2']))
        pairs = [(k['label'], k['formatted_value']) for k in kpis[:6]]
        for i in range(0, len(pairs), 3):
            story.append(_kpi_table(pairs[i:i+3], styles, UW))
            story.append(Spacer(1, 0.1*cm))

    # ── PAGE 3: AI Summary ────────────────────────────────────────────────────
    if data_summary:
        story.append(PageBreak())
        story.append(Paragraph('AI Executive Summary', styles['h2']))
        story.append(HRFlowable(width=UW, thickness=0.4,
                                color=C_BORDER, spaceAfter=8))
        clean = re.sub(r'\*\*(.+?)\*\*', r'\1', data_summary)
        clean = re.sub(r'#{1,6}\s*',     '',    clean)
        clean = re.sub(r'\n{3,}', '\n\n', clean).strip()
        for para in clean.split('\n\n'):
            if para.strip():
                story.append(Paragraph(para.strip(), styles['body']))
                story.append(Spacer(1, 0.1*cm))

    # ── PAGE 4: Visual Analytics ──────────────────────────────────────────────
    story.append(PageBreak())
    story.append(Paragraph('Visual Analytics', styles['h2']))
    story.append(Paragraph(
        'Automated charts generated from your dataset '
        'by the QueryMind analytics engine.',
        styles['muted']))
    story.append(Spacer(1, 0.2*cm))
    _add_charts(story, df, styles, figures=figures)

    # ── PAGE 5: Cleaning Report ───────────────────────────────────────────────
    if cleaning_report:
        cr = cleaning_report
        story.append(PageBreak())
        story.append(Paragraph('Smart Cleaning Report', styles['h2']))
        story.append(_kpi_table([
            ('Nulls Filled',       cr['total_nulls_filled']),
            ('Duplicates Removed', cr['duplicates_removed']),
            ('Columns Changed',    cr['columns_changed']),
            ('Rows After Clean',   f"{cr['rows_after']:,}"),
        ], styles, UW))
        story.append(Spacer(1, 0.35*cm))
        story.append(Paragraph('Per-Column Changes', styles['h2']))
        cr_rows = []
        for c in cr['columns']:
            ns = (f"{c['nulls_before']}→{c['nulls_after']} (−{c['nulls_filled']})"
                  if c['nulls_filled'] > 0 else str(c['nulls_before']))
            ts = (f"{c['dtype_before']}→{c['dtype_after']}"
                  if c['dtype_before'] != c['dtype_after']
                  else c['dtype_before'])
            us = (f"{c['unique_before']}→{c['unique_after']}"
                  if c['unique_before'] != c['unique_after']
                  else str(c['unique_before']))
            cr_rows.append([c['name'], ts, ns, us,
                            ' | '.join(c['actions']) or '—',
                            'Yes' if c['changed'] else '—'])
        story.append(_data_table(
            ['Column','Type','Nulls','Unique','Actions','Changed'],
            cr_rows, UW,
            col_widths=[3*cm,2.5*cm,2.5*cm,2*cm,4.5*cm,1.5*cm],
            fsz=7,
        ))

    # ── LAST PAGE: Column Schema ──────────────────────────────────────────────
    story.append(PageBreak())
    story.append(Paragraph('Column Schema', styles['h2']))
    story.append(_data_table(
        ['Column','Type','Non-Null','Nulls','Unique Values'],
        [[col, str(df[col].dtype),
          str(df[col].count()),
          str(int(df[col].isnull().sum())),
          str(df[col].nunique())]
         for col in df.columns],
        UW, col_widths=[4*cm,3*cm,3*cm,2.5*cm,3.5*cm],
    ))

    # ── Build ─────────────────────────────────────────────────────────────────
    doc.build(story,
              onFirstPage=on_first,
              onLaterPages=on_later)

    buf.seek(0)
    return buf.read()